### ISSUE TITLE
Feedback for “Web Development Setup”

### ISSUE THREAD

**Issue by bernardfernando** [TechEducatorsTeam/development-setup#1]
Excellent instructions.  When the computer I used for this was found to be too slow and was having issues, I decided to use a different computer. I managed to install sortware using these guides. Then configured with the help of Jez/Sam/Rich. Thanks so much.

**Comment by Illizian** [comment]
Thanks @bernardfernando, that's great to hear.

I hope you're excited for another week of learning, see you tomorrow!

**Comment by bernardfernando** [comment]
Yes Illizian, very straight forward instructions.  Thanks so much.
